GET http://localhost:3000/api/dev/tournament

###
POST http://localhost:3000/api/dev/tournament
Content-Type: application/json
Accept: application/json

{
    "tournamentCode": "ABCD1234",
    "tournamentName": "TournamentName",
    "status": "en curso",
    "startDate": "2024-10-01",
    "endDate": "2024-10-30",
    "nMaxParticipants": 10,
    "tags": "tag1",
    "userId": 1
}

    